### ISSUE TITLE
'Move Plots: Enabled' even though -move parameter is not passed.

### ISSUE THREAD

**Issue by Freekers** [SamuelNZ/SPlotter#4]
First of all, thank you very much for SPlotter, this is exactly what I've been looking for.

SPlotter shows that Move Plots is Enabled, even though I'm not passing the -move parameter in the commandline: https://i.imgur.com/unpTISN.png

.bat file contents:
`SPlotter.exe -id 6168836050058294549 -sn 10000000000000 -n 102400 -t 1 -path C:\plots1 -mem 1G -repeat 2000`

**Comment by SamuelNZ** [comment]
Hey man you're more than welcome,

I've just picked up on this when I was looking at my plotter machine, It's just a visual bug and will be fixed in the next version :)

Let me know if you have any other problems or suggestions

Thanks,
Samuel.

**Comment by SamuelNZ** [comment]
Thanks for pointing this out, Should be fixed now.

Funny how 1 = sign can make all the difference.

**Comment by SamuelNZ** [comment]
Hey man you're more than welcome,

This is fixed now, Please download **v1.8.2**

Let me know if you have any other problems or suggestions and thank you for your help.

Thanks,
Samuel.

**Comment by Freekers** [comment]
Thanks for the quick fix!
