### ISSUE TITLE
Feature Request: On plot completion, execute .bat file

### ISSUE THREAD

**Issue by Freekers** [SamuelNZ/SPlotter#6]
I use cloud storage for my plots, i.e. no local disks. On completion of the plots, I need to upload them using a third party tool which can be called from a .bat file. Therefore it would be awesome if I can have SPlotter to call this .bat file after a plot finishes. 

Now I have a workaround in place to make this happen: SPlotter moves plots to a different directory which is watched by a Directorywatcher tool. That tool calls the .bat file to upload the plot to cloud storage.

**Comment by SamuelNZ** [comment]
That could cause issues with anti-virus program heuristics and I can see several ways that could lead to abuse so I won't be adding it, Sorry... 

Glad your other feature request was already a feature aha.
